Raise minimum tested version to rustc 1.34
Required by use of TryInto in rand_core.

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
      --> .cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.6.1/src/le.rs:14:5
       |
    14 | use core::convert::TryInto;
       |     ^^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
      --> .cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.6.1/src/le.rs:21:41
       |
    21 |         *out = u32::from_le_bytes(chunk.try_into().unwrap());
       |                                         ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
      --> .cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.6.1/src/le.rs:30:41
       |
    30 |         *out = u64::from_le_bytes(chunk.try_into().unwrap());
       |                                         ^^^^^^^^