Raise minimum tested version to rustc 1.36
Required for extern crate alloc in rand_core.

    error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
      --> .cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.6.1/src/lib.rs:45:27
       |
    45 | #[cfg(feature = "alloc")] extern crate alloc;
       |                           ^^^^^^^^^^^^^^^^^^^